[versions]
mod-version = "Final"

# Fabric (https://fabricmc.net/develop)
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.3"
fabric-loader = "0.18.2"
fabric-api = "0.139.0+1.21.11"

# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.14-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client/)
meteor = "1.21.11-SNAPSHOT"

# Baritone
baritone = "1.21.11-SNAPSHOT"

# Mods
xaeroplus = "2.30.8+fabric-1.21.11"
xaeros-worldmap = "fabric-1.21.11-1.40.11"
xaeros-minimap = "fabric-1.21.11-25.3.10"

# Libraries
lambdaevents = "2.4.2"
caffeine = "3.1.8"

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }
baritone = { module = "meteordevelopment:baritone", version.ref = "baritone" }

# Mods
xaeroplus = { module = "maven.modrinth:xaeroplus", version.ref = "xaeroplus" }
xaeros-worldmap = { module = "maven.modrinth:xaeros-world-map", version.ref = "xaeros-worldmap" }
xaeros-minimap = { module = "maven.modrinth:xaeros-minimap", version.ref = "xaeros-minimap" }

# Libraries
lambdaevents = { module = "net.lenni0451:LambdaEvents", version.ref = "lambdaevents" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
